##
# Makefile
# Author: Kenta Ishii
# License: MIT
# License URL: https://opensource.org/licenses/MIT
##

# make PRODUCT:=__RASPI2B=1
# make PRODUCT:=__RASPIZEROW=1

include ../share/aloha_raspi/aloha32.mk
